#!/usr/bin/python

# Importa funciones del sistema
import sys
import os
# Importa funciones de tiempo
import time
# Importa funciones de usuario
import pwd
# Importa funciones de MySQL
import MySQLdb

db = MySQLdb.connect(host="localhost", user="root", passwd="1025874369", db="ottodb") #Conecta a DB

cur = db.cursor() #Crea el cursor

fecha = time.strftime("%d%m%y_%H%M%S")
pitch = "-p 5"
export = "-w /var/www/html/sound/last_voice_"+fecha+".wav"
mensaje = sys.argv[1]
user = pwd.getpwuid(os.getuid())[0]

#Escribe el mensaje en el fichero
file = open("/var/www/html/voicelog.html","a")#a = modo append (agrega al final del archivo)
file.write("<div style=\"color: #FFF; background: #111\">[" + time.strftime("%d/%m/%y %H:%M:%S") + "]>>>" + user + ": " + mensaje + "<br></div>")
file.close()

#Escribe el mensaje en la DB
cur.execute("""INSERT INTO `voicelog`(`id`,`fecha`,`dir`,`mensaje`) VALUES (NULL, NULL, %s, %s)""",("out",mensaje))
db.commit()
cur.close()

#Genera el archivo de audio, lo reproduce y lo convierte a MP3

os.system("cd /var/www/html/sound && rm -f *")						# Elimina los archivos anteriores
file = open("/var/www/html/sound/lastvoice.txt","w")#w = write (borra todo y escribe)	# Registra el ultimo cambio
file.write(fecha)
file.close()
os.system("sudo espeak -ves-la "+pitch+" "+export+" \'"+mensaje+"\' 2>/dev/null")	# Exporta la voz sintetizada
os.system("sudo aplay -D plughw:1 /var/www/html/sound/last_voice_"+fecha+".wav")	# Reproduce el nuevo archivo
os.system("sudo lame /var/www/html/sound/last_voice_"+fecha+".wav /var/www/html/sound/last_voice_"+fecha+".mp3") # Convierte a MP3
